-- This migration version is intentionally a no-op.
--
-- The lesson-comments community schema was already applied remotely by
-- 20260927060207_lesson_comments_community.sql. Re-running the original
-- statements here fails because objects such as lesson_comments_parent_idx
-- already exist.
--
-- Keep this migration file so the local migration history remains intact.
-- `supabase db push` can record this version as applied without changing the
-- database schema. Do not add schema changes here; create a new migration
-- with a new timestamp for future changes.
